### ISSUE TITLE
Can't get it to compile in XCode 4.6

### ISSUE THREAD

**Issue by curyous** [phoboslab/JavaScriptCore-iOS#4]
When compiling the release version of WTF iOS for iPhone 6.0 Simulator, I get errors in FastMalloc.cpp.  Any idea how to fix the errors?

.../XCode Projects/JavaScriptCore-iOS/WTF/wtf/FastMalloc.cpp:2477:8: error: private field 'pad_' is not used [-Werror,-Wunused-private-field]
  char pad_[(64 - (sizeof(TCMalloc_Central_FreeList) % 64)) % 64];

.../XCode Projects/JavaScriptCore-iOS/WTF/wtf/FastMalloc.cpp:4544:31: error: private field 'm_reader' is not used [-Werror,-Wunused-private-field]
    const RemoteMemoryReader& m_reader;
